[package]
name = "glenside"
version = "0.1.0"
authors = ["Gus Smith <guscomps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
run-on-github-actions = []

defaults = []

[dependencies]
approx = "0.3.2"
either = "1.5.3"
itertools = "0.9.0"
env_logger = "0.7.1"
log = "0.4.8"
ndarray-npy = "0.5.0"
num-traits = "0.2.11"
serde_json = "1.0"
test-logger = "0.1.0"
clap = "2.33.1"
rand = "0.7.3"

[dependencies.egg]
rev = "46de9eb1e05b6e86a9ee0b0fd03000b1b039f107"
git = "https://github.com/mwillsey/egg"

[dependencies.ndarray]
version = "0.13.0"
features = ["approx"]

[dependencies.serde]
version = "1.0"
features = ["derive"]