[package]
name = "glenside"
version = "0.1.0"
authors = ["Gus Smith <guscomps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['tvm']

run-on-github-actions = []

[dependencies]
approx = "0.3.2"
either = "1.5.3"
itertools = "0.9.0"
env_logger = "0.7.1"
log = "0.4.8"
ndarray-npy = "0.6.0"
num-traits = "0.2.11"
serde_json = "1.0"
test-logger = "0.1.0"
clap = "2.33.1"
rand = "0.7.3"
ndarray-rand = "0.11.0"
ordered-float = "2.0.0"


[dependencies.tvm]
# TODO(@gussmith23) Change this to tvm mainline
# once https://github.com/apache/incubator-tvm/pull/6563 is merged
rev = "3b6edf9ec0b6b3ab6a91174e7e2aa321cd8ec9b2"
git = "https://github.com/mwillsey/incubator-tvm"
optional = true

[dependencies.egg]
rev = "39415f19acdacd6dde62f40cb2bb08f8669acc85"
git = "https://github.com/mwillsey/egg"

[dependencies.ndarray]
version = "0.13.0"
features = ["approx"]

[dependencies.serde]
version = "1.0"
features = ["derive"]