name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --tag glenside .
      # TODO(@gussmith23) Figure out a better way to signal "test everything"
      # The main problem with --all-features is that I currently use feature
      # flags to indicate things that aren't necessarily "additional features".
      # For example, I have a feature that indicates that we're running on
      # GitHub actions, which changes timeouts in some places. So if the feature
      # was instead "--not-running-on-github-actions", then --all-features
      # wouldn't make much sense.
      - run: docker run glenside cargo test --all-features
