name: Check formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-formatting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
