# This is a basic workflow to help you get started with Actions

name: TODOs to GitHub Issue

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  todos-to-issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Find and format TODOs
      id: generate-todos
      run: |
        find . -name '*.rs' | xargs grep -n TODO | sed 's/^\(.*\):\([0-9]*\):.*TODO\((\(.*\))\)\{0,1\} *\(.*\)$/- (\4) [\5](\1#L\2)/' > todos.txt
        result=$(cat todos.txt)
        result="${result//'%'/'%25'}"
        result="${result//$'\n'/'%0A'}"
        result="${result//$'\r'/'%0D'}" 
        echo ::set-output name=result::$result

    - name: Add test report comment on PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: 1
        comment-id: 640962463
        edit-mode: replace
        body: |
          These TODOs were scraped from the code.
          
          ${{ steps.generate-todos.outputs.result }}
        reaction-type: 'eyes'
